import unittest
import os
import csv
import glob
import shutil
from generate_csv import generate_csv

class TestGenerateCSV(unittest.TestCase):

    def setUp(self):
        self.output_dir = "/app/output/test_generate"
    
    def tearDown(self):
        # Cleanup: Remove the test output directory and its contents if it exists
        if os.path.exists(self.output_dir):
            shutil.rmtree(self.output_dir)

    def test_generate_csv(self):
        generate_csv(0.001, self.output_dir)  # Approx 1MB file for testing

        # Find the part file generated by Spark
        part_files = glob.glob(f"{self.output_dir}/part-*")
        self.assertTrue(part_files, "No part files found in output directory")

        with open(part_files[0], 'r') as f:
            reader = csv.reader(f)
            rows = list(reader)
        
        # Check that each row has exactly four fields
        self.assertTrue(all(len(row) == 4 for row in rows[1:]))

if __name__ == "__main__":
    unittest.main()
